

language: ruby
rvm:
  - 2.0

# only run CI-builds on master branch
branches:
  only:
  - master

# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild.sh
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild.sh
exclude: [vendor]
sudo: false


travis encrypt GH_TOKEN=f12782fe0297406b19dfacce2d96f25ac169b04e
